[package]
name = "matching-engine"
version = "0.8.3"
edition = "2021"

[dependencies]
tokio = { version = "1.38", features = ["rt-multi-thread", "macros", "signal"] }
axum = "0.7"
prometheus = "0.13"
once_cell = "1.19"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
