apiVersion: v1
kind: ConfigMap
metadata:
  name: ch-ddl
  namespace: trading
data:
  01_trades.sql: |
    CREATE TABLE IF NOT EXISTS trades_raw
    (
      trade_id String,
      order_id String,
      symbol   LowCardinality(String),
      side     Enum8('buy' = 1, 'sell' = 2),
      price    Decimal(20,8),
      qty      Decimal(20,8),
      ts       DateTime64(3),
      _ingested_at DateTime DEFAULT now()
    )
    ENGINE = MergeTree
    PARTITION BY toDate(ts)
    ORDER BY (symbol, ts, trade_id)
    TTL ts + INTERVAL 90 DAY DELETE;

    CREATE MATERIALIZED VIEW IF NOT EXISTS trades_mv
    TO trades
    AS SELECT
      trade_id, order_id, symbol, side, price, qty, ts
    FROM trades_raw;

    CREATE TABLE IF NOT EXISTS trades
    (
      trade_id String,
      order_id String,
      symbol   LowCardinality(String),
      side     Enum8('buy' = 1, 'sell' = 2),
      price    Decimal(20,8),
      qty      Decimal(20,8),
      ts       DateTime64(3)
    )
    ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/trades','{replica}')
    PARTITION BY toDate(ts)
    ORDER BY (symbol, ts, trade_id)
    TTL ts + INTERVAL 365 DAY DELETE
    SETTINGS index_granularity = 8192;
