apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata: { name: matching-kafka-lag, namespace: trading }
spec:
  scaleTargetRef: { name: svc-matching-engine }
  pollingInterval: 10
  cooldownPeriod:  120
  minReplicaCount: 2
  maxReplicaCount: 20
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: "{{ .KAFKA_BROKERS }}"
        consumerGroup: "matching-engine"
        topic: "orders.in"
        lagThreshold: "2000"
