apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: matching-engine-slo
  namespace: trading
  labels: { release: kube-prometheus-stack }
spec:
  groups:
  - name: matching.slo
    rules:
    - alert: MatchingP95LatencyHigh
      expr: histogram_quantile(0.95, sum by (le) (rate(batch_latency_ms_bucket[5m]))) > 50
      for: 10m
      labels: { severity: page }
      annotations: { summary: "Matching p95 > 50ms (10m)" }
    - alert: MatchingBackpressureActive
      expr: matching_backpressure_active > 0
      for: 5m
      labels: { severity: ticket }
      annotations: { summary: "Backpressure engaged > 5m" }
    - alert: MatchingDLQ
      expr: increase(matching_dlq_total[10m]) > 0
      for: 0m
      labels: { severity: warn }
      annotations: { summary: "DLQ increment detected" }
