apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: svc-matching-engine
  namespace: trading
  labels: { release: kube-prometheus-stack }
spec:
  selector: { matchLabels: { app: svc-matching-engine } }
  namespaceSelector: { matchNames: ["trading"] }
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
